- id: d9872d0607fe426f9b999f3691acdfa2
  alias: Motive - Timer Toggle Handler
  description: Startet oder stoppt den Timer
  trigger:
  - platform: state
    entity_id: input_boolean.motive_timer_active
    from: 'off'
    to: 'on'
    id: timer_start
  - platform: state
    entity_id: input_boolean.motive_timer_active
    from: 'on'
    to: 'off'
    id: timer_stop
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: timer_start
      sequence:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.motive_timer_start
        data:
          datetime: '{{ now() }}'
      - service: timer.start
        target:
          entity_id: timer.motive_work_timer
        data:
          duration: 08:00:00
      - service: persistent_notification.create
        data:
          title: ⏱️ Timer gestartet
          message: 'Kategorie: {{ states(''input_text.motive_active_category'') }}'
    - conditions:
      - condition: trigger
        id: timer_stop
      sequence:
      - service: timer.cancel
        target:
          entity_id: timer.motive_work_timer
      - variables:
          start_time: '{{ states(''input_datetime.motive_timer_start'') }}'
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ start_time not in [''unknown'', ''unavailable'', '''']
              }}'
          sequence:
          - variables:
              elapsed_seconds: '{{ (as_timestamp(now()) - as_timestamp(start_time))
                | int }}'
              elapsed_minutes: '{{ (elapsed_seconds / 60) | int }}'
              current_total: '{{ states(''input_number.motive_time_tracked_today'')
                | int }}'
              new_total: '{{ [current_total + elapsed_minutes, 1440] | min }}'
          - service: input_number.set_value
            target:
              entity_id: input_number.motive_time_tracked_today
            data:
              value: '{{ new_total }}'
          - service: persistent_notification.create
            data:
              title: ⏹️ Timer gestoppt
              message: '{{ elapsed_minutes }} Minuten getrackt

                Heute gesamt: {{ new_total }} Minuten

                '
  mode: single
- id: b80cb47ec90a47b8919584669b1f2d46
  alias: Motive - Kategorie Selection
  description: Nur eine Kategorie kann aktiv sein
  trigger:
  - platform: state
    entity_id:
    - input_boolean.motive_cat_work
    - input_boolean.motive_cat_privat
    - input_boolean.motive_cat_coding
    - input_boolean.motive_cat_design
    - input_boolean.motive_cat_engineering
    to: 'on'
  condition: []
  action:
  - variables:
      triggered_entity: '{{ trigger.entity_id }}'
      category_map:
        input_boolean.motive_cat_work: Work
        input_boolean.motive_cat_privat: Privat
        input_boolean.motive_cat_coding: Coding
        input_boolean.motive_cat_design: Design
        input_boolean.motive_cat_engineering: Engineering
      selected_category: '{{ category_map[triggered_entity] }}'
  - service: input_text.set_value
    target:
      entity_id: input_text.motive_active_category
    data:
      value: '{{ selected_category }}'
  - service: input_boolean.turn_off
    target:
      entity_id: "{% set entities = [\n  'input_boolean.motive_cat_work',\n  'input_boolean.motive_cat_privat',
        \n  'input_boolean.motive_cat_coding',\n  'input_boolean.motive_cat_design',\n
        \ 'input_boolean.motive_cat_engineering'\n] %} {{ entities | reject('eq',
        triggered_entity) | list }}\n"
  mode: single
- id: 43ac83b7ca764df298d90fafc9e6c212
  alias: Motive - Daily Reset
  description: Reset um Mitternacht mit Streak Logic
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - variables:
      goal_reached: '{{ states(''sensor.motive_goal_progress'') | float(0) >= 100
        }}'
      sick_mode: '{{ states(''input_boolean.motive_sick_mode'') == ''on'' }}'
      yesterday: '{{ (now() - timedelta(days=1)).strftime(''%Y-%m-%d'') }}'
      progress: '{{ states(''sensor.motive_goal_progress'') | float(0) }}'
      minutes: '{{ states(''input_number.motive_time_tracked_today'') | int }}'
  - service: input_text.set_value
    target:
      entity_id: input_text.motive_history_data
    data:
      value: "{% set history = states('input_text.motive_history_data') %} {% if history
        in ['unknown', 'unavailable', '', '{}'] %}\n  {% set history = '{}' %}\n{%
        endif %} {% set data = history | from_json %} {% set _ = data.update({\n  yesterday:
        {\n    'percent': progress | round(1),\n    'minutes': minutes,\n    'sick':
        sick_mode\n  }\n}) %} {% set keys = data.keys() | list | sort %} {% if keys
        | length > 365 %}\n  {% set _ = data.pop(keys[0]) %}\n{% endif %} {{ data
        | to_json }}\n"
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ sick_mode }}'
      sequence:
      - service: persistent_notification.create
        data:
          title: "\U0001F3E5 Krankheitstag"
          message: Streak bleibt bei {{ states('input_number.motive_streak_counter')
            }} Tagen
    - conditions:
      - condition: template
        value_template: '{{ goal_reached }}'
      sequence:
      - service: input_number.increment
        target:
          entity_id: input_number.motive_streak_counter
      - service: persistent_notification.create
        data:
          title: "\U0001F525 Streak!"
          message: '{{ states(''input_number.motive_streak_counter'') }} Tage in Folge!'
    default:
    - service: input_number.set_value
      target:
        entity_id: input_number.motive_streak_counter
      data:
        value: 0
    - service: persistent_notification.create
      data:
        title: "\U0001F494 Streak verloren"
        message: Neuer Start heute!
  - service: input_number.set_value
    target:
      entity_id: input_number.motive_time_tracked_today
    data:
      value: 0
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.motive_sick_mode
  - service: input_text.set_value
    target:
      entity_id: input_text.motive_active_category
    data:
      value: Keine
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.motive_cat_bega
      - input_boolean.motive_cat_privat
      - input_boolean.motive_cat_coding
      - input_boolean.motive_cat_design
      - input_boolean.motive_cat_engineering
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.motive_timer_active
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.motive_last_reset
    data:
      datetime: '{{ now() }}'
  mode: single
- id: 897a07fd75a74783a18164b261ba3d88
  alias: Motive - Save Daily Achievement
  description: Speichert Tagesfortschritt für Heatmap
  trigger:
  - platform: time
    at: '23:59:00'
  condition: []
  action:
  - service: input_number.set_value
    target:
      entity_id: input_number.motive_daily_achievement
    data:
      value: '{{ states(''sensor.motive_goal_progress'') | float(0) }}'
  mode: single
- id: bd4a3f2ab8e94c4e883caf4837aea542
  alias: Motive - Goal Reached Notification
  description: Benachrichtigung wenn 100% erreicht
  trigger:
  - platform: numeric_state
    entity_id: sensor.motive_goal_progress
    above: 99.9
  condition:
  - condition: state
    entity_id: input_boolean.motive_sick_mode
    state: 'off'
  - condition: template
    value_template: '{{ (now() - this.attributes.last_triggered | default(as_datetime(0)))
      > timedelta(hours=20) }}

      '
  action:
  - service: persistent_notification.create
    data:
      title: "\U0001F389 Tagesziel erreicht!"
      message: 'Glückwunsch! Du hast dein Ziel erreicht!

        Getrackt: {{ states(''input_number.motive_time_tracked_today'') }} Minuten

        Streak: {{ states(''input_number.motive_streak_counter'') }} Tage

        '
  mode: single
